### ISSUE TITLE
Async version of the driver

### ISSUE THREAD

**Issue by falk-h** [tkeksa/lis2dh12#6]
Hi!

I've created an async version of the driver for use with [embassy](https://github.com/embassy-rs/embassy). I've basically just factored out some shared data structures from the synchronous driver, copied it, and sprinkled in a bunch of `async` and `.await`. I've also had to remove the `accelerometer` trait implementations from the async version of the driver since there doesn't seem to be an async equivalent of those traits anywhere.

Would you be interested in upstreaming this?

**Comment by falk-h** [comment]
For the record, [here's the async version of the driver](https://github.com/thetc-elevate/lis2dh12).

**Comment by kyrias** [comment]
@tkeksa Ping, this would be very useful.

@falk-h If the answer is no or there's no reply, any chance you could publish a pure async version as `lis2dh12-async` instead?

**Comment by tkeksa** [comment]
As the sync and async versions are quite different I do not plan to support async variant. But feel free to reuse my code for new async crate.

**Comment by svenstaro** [comment]
@hulthe Would you mind publishing your version as `lis2dh12-async` on crates.io? It would be really appreciated.

**Comment by falk-h** [comment]
@kyrias Sorry, I'm no longer involved with the project that prompted this PR. I'll go ahead and close this, since there's no interest in merging the async variant.
